<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-03-22 23:03
=======
# Generated by Django 2.2.28 on 2026-03-27 00:53
>>>>>>> user-authentication

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=30)),
                ('tags', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
<<<<<<< HEAD
=======
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundbytes.Album')),
                ('genres', models.ManyToManyField(to='soundbytes.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=soundbytes.models.profile_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=soundbytes.models.banner_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('user_type', models.CharField(choices=[('LISTENER', 'Music Listener'), ('ARTIST', 'Musician/Artist')], default='LISTENER', max_length=10)),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified_artist', models.BooleanField(default=False)),
                ('date_joined_profile', models.DateTimeField(auto_now_add=True)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('total_likes_received', models.PositiveIntegerField(default=0)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_joined_profile'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=255)),
                ('songs', models.ManyToManyField(to='soundbytes.Song')),
>>>>>>> user-authentication
            ],
        ),
    ]
