# Generated by Django 2.2.28 on 2026-03-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundbytes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='title',
            new_name='playlist_title',
        ),
    ]
