# Generated by Django 2.2.28 on 2026-03-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundbytes', '0002_auto_20260323_2333'),
        ('soundbytes', '0003_album_remove_song_cover_image_song_album'),
    ]

    operations = [
    ]
