# Generated by Django 6.0.3 on 2026-03-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbytes', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
