# Generated by Django 2.2.28 on 2026-03-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundbytes', '0005_post_like_count'),
        ('soundbytes', '0002_auto_20260323_2333'),
    ]

    operations = [
    ]
